### ISSUE TITLE
Restrição de Entrada não respeitada

### ISSUE THREAD

**Issue by VictorKoehler** [ifpb/maratona-pop#22]
Dois casos de testes não respeitam a restrição de entrada do *Problema C - Coeficientes* da [Seletiva POP 2018](../blob/master/ID-097-2018-10-Seletiva-POP-2018/_prova.pdf):
- [2](../blob/master/ID-097-2018-10-Seletiva-POP-2018/c_coeficientes/input/02): N > 20
- [4](../blob/master/ID-097-2018-10-Seletiva-POP-2018/c_coeficientes/input/04): N > 20

**Comment by tgouveia** [comment]
Alterada a descrição do problema no arquivo _prova.pdf.
